import {COLOR, FAMILY, SIZE} from '../../../theme/typography';

const React = require('react-native');
const {Platform} = React;

export default {
  bookingHeader: {
    backgroundColor: COLOR.PRIMARY,
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  bookingHeaderTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_20,
    color: COLOR.LIGHT,
    marginTop: 15,
    marginLeft: 15,
    paddingBottom: 5,
  },
  bookingHeaderText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.BLUE,
    marginLeft: 15,
    textAlign: 'center',
  },
  bookingContainer: {
    marginHorizontal: 20,
    marginTop: 30,
  },
  bookingContent: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    marginVertical: 10,
  },
  bookingDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  bookingIdText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    marginBottom: 3,
  },
  completeBtn: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    backgroundColor: COLOR.GREEN,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  bookingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: COLOR.GREYLIGHT,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  bookingTitle: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_11,
    color: COLOR.DARKBLUE,
  },
  bookingTextDark: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_11,
    color: COLOR.GREYVIOLET,
  },
  bookingText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.GREYVIOLET,
    paddingLeft: 5,
  },
  documentInfo: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    marginVertical: 15,
  },
  documentText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    paddingHorizontal: 15,
    paddingTop: 15,
  },
  checkoutText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.SMOKEVIOLET,
    marginBottom: 20,
    paddingHorizontal: 15,
  },
  driverDetail: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    marginBottom: 20,
  },
  driverInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  driverText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    paddingLeft: 15,
  },
  driverTextInfo: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.SMOKEVIOLET,
    marginBottom: 20,
    paddingLeft: 15,
  },
  driverImg: {
    width: 50,
    height: 50,
    borderRadius: 50,
    marginRight: 15,
    marginTop: 10,
  },
  mailBtnInfo: {
    flexDirection: 'row',
    marginVertical: 10,
    marginHorizontal: 20,
  },
  mailBtn: {
    flex: 5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.GREEN,
    borderRadius: 5,
  },
  mailInvoiceBtn: {
    flex: 2,
    paddingVertical: 15,
    borderRadius: 5,
    marginLeft: 10,
    paddingLeft: 15,
    backgroundColor: COLOR.BLUE,
  },
  tripText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
  },
  ratingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
  },
  ratingIconSelected: {
    fontSize: SIZE.SIZE_20,
    color: 'rgb(234, 201, 78)',
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  ratingIcon: {
    fontSize: SIZE.SIZE_20,
    color: COLOR.SMOKEDARK,
    paddingHorizontal: 2,
    // dingVertical: 2,
  },
  modalRating: {
    width: '90%',
    height: 400,
    borderRadius: 20,
    backgroundColor: COLOR.LIGHT,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalRatingContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
  },
  modalHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFF3E0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  modalHeaderIcon: {
    fontSize: 24,
    color: '#FF9800',
  },
  modalHeaderTextContainer: {
    flex: 1,
  },
  modalTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_16,
    color: COLOR.DARK,
    marginBottom: 2,
  },
  modalSubtitle: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_11,
    color: COLOR.SMOKEVIOLET,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeIcon: {
    fontSize: 20,
    color: COLOR.GREYVIOLET,
  },
  formSection: {
    flex: 1,
    marginBottom: 15,
  },
  formLabel: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    marginBottom: 10,
  },
  formTextArea: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E8E8E8',
    paddingHorizontal: 15,
    paddingVertical: 12,
    minHeight: 140,
    textAlignVertical: 'top',
  },
  attachmentPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E3F2FD',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 10,
  },
  attachmentIcon: {
    fontSize: 18,
    color: COLOR.BLUE,
    marginRight: 8,
  },
  attachmentText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_11,
    color: COLOR.BLUE,
    flex: 1,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  attachButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  attachButtonText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.GREYVIOLET,
    marginLeft: 6,
  },
  buttonIcon: {
    fontSize: 18,
    color: COLOR.GREYVIOLET,
  },
  sendButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLOR.PRIMARY,
    borderRadius: 12,
    paddingVertical: 14,
    shadowColor: COLOR.PRIMARY,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  sendButtonText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    marginRight: 6,
  },
  sendButtonIcon: {
    fontSize: 16,
    color: COLOR.LIGHT,
  },
  modalComplainContainer: {
    position: 'relative',
    height: 200,
  },
  closeSortDesc: {
    alignItems: 'flex-end',
    marginVertical: 10,
  },
  formRow: {
    marginVertical: 10,
  },
  formText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    marginBottom: 10,
  },
  formInput3: {
    width: '100%',
    height: 50,
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    backgroundColor: COLOR.LIGHTVIOLET,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  accOrderInfo: {
    borderColor: COLOR.LIGHT,
    borderWidth: 1,
    borderTopWidth: 0,
    backgroundColor: COLOR.LIGHT,
    paddingVertical: 15,
    marginBottom: 20,
    borderRadius: 5,
  },
  accText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.PRIMARY,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderColor: COLOR.LIGHTVIOLET,
  },
  accordionBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 15,
    marginBottom: 10,
  },
  accordionTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARKBLUE,
  },
  accordion: {
    width: '100%',
    marginBottom: 5,
  },
};
