import { COLOR, FAMILY, SIZE } from '../../../theme/typography';

const React = require('react-native');

export default {
  // --content--//

  homeContainer: {
    backgroundColor: '#F5F7FA', // Verified lighter background for better contrast
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 30,
  },
  btnIcon: {
    alignItems: 'center',
    margin: 10,
    marginTop: 20,
    color: 'black',
  },
  formRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'black',

    borderRadius: 3,
    marginBottom: 20,
    marginHorizontal: 20,
    paddingLeft: 20,
  },
  formInput: {
    flex: 1,
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.PRIMARY,
    marginLeft: 5,
  },
  footerBtn: {
    backgroundColor: COLOR.PRIMARY,
  },
  footerBtnInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 20,
  },
  selectBtn: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.GREEN,
    borderRadius: 3,
    marginRight: 5,
    paddingVertical: 15,
  },
  shareBtn: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLOR.BLUE,
    borderRadius: 3,
    paddingVertical: 15,
    marginLeft: 5,
  },
  shareBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
  },
  biddingCardText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: 'black',
    marginBottom: 1,
  },
  // --map--//
  mMap: {
    width: '100%',
    height: '100%',
    borderColor: COLOR.LIGHT,
    borderWidth: 1,
  },
  mMapImg: {
    flex: 1,
  },
  headerImg: {
    marginTop: -20,
    width: 62,
    height: 62,
    borderRadius: 36,
  },
  bookingBtn: {
    backgroundColor: COLOR.GREEN,
    borderRadius: 5,
    marginVertical: 10,
    marginHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookingBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    textAlign: 'center',
    paddingVertical: 15,
  },
  /* -- Accordion -- */
  tripsAllLable: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
  },
  accordionTab: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  accordionTabText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: '#333',
  },

  /** Content */
  myTripContainer: {
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  openBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: 12,
    color: COLOR.LIGHT,
    alignSelf: 'center',
    backgroundColor: COLOR.BLUE,
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 3,
  },
  completedBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    alignSelf: 'center',
    backgroundColor: COLOR.GREEN,
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 3,
  },
  bookingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: COLOR.SMOKELIGHT,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  bookingTitle: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARKBLUE,
  },
  bookingDetailInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bookingDetail: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    borderColor: COLOR.GREY,
    borderRightWidth: 1,
    paddingRight: 5,
  },
  bookingText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.GREYVIOLET,
    borderColor: COLOR.GREY,
    paddingLeft: 5,
  },
  btnInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: 15,
  },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'red',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginRight: 10,
  },
  cancelBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    marginLeft: 5,
  },
  detailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: COLOR.SMOKELIGHT,
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginRight: 10,
  },
  detailBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.GREYDARK,
    marginLeft: 5,
  },
  detailTag: {
    flex: 1,
  },
  balanceBtn: {
    flex: 1,
  },
  balanceBtnText: {
    backgroundColor: COLOR.GREEN,
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    textAlign: 'center',
    backgroundColor: 'rgba(249,64,65,1)',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  rateBtn: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    textAlign: 'center',
    backgroundColor: COLOR.PRIMARY,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  /** * -- ModalLayout -- ***/
  modalRating: {
    width: '90%',
    height: 400,
    borderRadius: 10,
    zIndex: 2,
  },
  modalRatingContainer: {
    marginHorizontal: 15,
  },
  closeSortDesc: {
    alignItems: 'flex-end',
    marginVertical: 10,
  },
  starImg: {
    width: 80,
    height: 80,
    alignSelf: 'center',
  },
  modalRatingTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_20,
    color: COLOR.DARKLIGHT,
    alignSelf: 'center',
    paddingTop: 10,
    paddingBottom: 5,
  },
  modalRatingText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.GREYVIOLET,
    alignSelf: 'center',
    textAlign: 'center',
    lineHeight: 20,
  },
  modalRatingInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 20,
  },
  modalStarIcon: {
    fontSize: SIZE.SIZE_30,
    color: 'rgba(255, 178, 41, 1)',
    paddingHorizontal: 5,
    paddingVertical: 5,
  },
  submitBtn: {
    backgroundColor: COLOR.GREEN,
    paddingVertical: 15,
    borderRadius: 5,
    marginVertical: 15,
  },
  submitBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    textAlign: 'center',
  },
  /** * -- Accordion -- ***/
  saccordionContent: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    paddingVertical: 15,
    marginTop: 5,
  },
  accordion: {
    width: '100%',
    marginBottom: 5,
  },
  accordionBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  accordionTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARKBLUE,
  },
  accOrderInfo: {
    borderColor: COLOR.LIGHT,
    borderWidth: 1,
    borderTopWidth: 0,
    backgroundColor: COLOR.LIGHT,
    borderRadius: 5,
    paddingVertical: 15,
    marginBottom: 20,
  },
  accText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.PRIMARY,
    borderBottomWidth: 1,
    borderColor: COLOR.LIGHTVIOLET,
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  accordionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  accordionActiveText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    backgroundColor: 'rgba(53,190,224,1)',
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  accordionInactiveText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
    backgroundColor: 'rgba(92,186,71,1)',
    borderRadius: 15,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  senderPic: {
    marginHorizontal: 10,
  },
  reciverPic: {
    marginHorizontal: 10,
  },
  wrapimg: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  profileImg: {
    width: 32,
    height: 32,
    borderRadius: 45,
  },

  sender: {
    minWidth: '1%',
    maxWidth: '80%',
    alignItems: 'flex-end',
    backgroundColor: COLOR.GREY,
    marginTop: 5,
    paddingBottom: 5,
    marginLeft: 'auto',
    paddingTop: 5,
    paddingRight: 10,
    borderRadius: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chatText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.LIGHT,
  },

  reciver: {
    minWidth: '1%',
    maxWidth: '80%',
    marginTop: 5,
    paddingBottom: 5,
    borderRadius: 6,
    paddingTop: 5,
    paddingLeft: 7,
    marginRight: 'auto',
    fontSize: SIZE.SIZE_12,
    backgroundColor: COLOR.BLUE,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  formInput3: {
    width: '90%',
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
    backgroundColor: COLOR.LIGHTVIOLET,
    borderRadius: 3,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },

  noTripsFoundContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 100,
    paddingHorizontal: 30,
  },
  noTripsFoundIcon: {
    fontSize: 70,
    color: '#CBD5E0', // Soft grey for the icon
    marginBottom: 20,
  },
  noTripsFoundText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_20,
    color: COLOR.DARK,
    marginBottom: 10,
    textAlign: 'center',
  },
  noTripsFoundSubText: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_14,
    color: COLOR.GREYVIOLET,
    textAlign: 'center',
    lineHeight: 22,
  },
  listHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
    marginBottom: 15,
  },
  listHeaderTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_18,
    color: COLOR.DARK,
  },
  listHeaderCount: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.PRIMARY,
    backgroundColor: COLOR.SMOKEBLUE,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    overflow: 'hidden',
  },
  welcomeContainer: {
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  welcomeTitle: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_24,
    color: COLOR.DARK,
  },
  welcomeSubtitle: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_14,
    color: COLOR.GREYVIOLET,
  },

  // -- New BiddingCard Styles --
  cardContainer: {
    backgroundColor: COLOR.LIGHT,
    borderRadius: 8,
    marginVertical: 2,
    marginHorizontal: 0,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  cardAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 10,
  },
  cardHeaderInfo: {
    flex: 1,
  },
  cardName: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_14,
    color: COLOR.DARK,
    marginBottom: 2,
  },
  cardCity: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_11,
    color: COLOR.GREYVIOLET,
  },
  cardPrice: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_16,
    color: COLOR.PRIMARY,
  },
  routeContainer: {
    marginBottom: 5,
  },
  routeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  routeItem: {
    flex: 1,
  },
  locationRow: {
    marginBottom: 4,
  },
  locationLabel: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_9,
    color: COLOR.GREYVIOLET,
    marginBottom: 2,
    textTransform: 'uppercase',
  },
  locationText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_12,
    color: COLOR.DARK,
  },
  detailGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
    backgroundColor: '#F8F9FA',
    borderRadius: 6,
    padding: 5,
  },
  detailItem: {
    flex: 1,
  },
  detailLabel: {
    fontFamily: FAMILY.REGULAR,
    fontSize: SIZE.SIZE_9,
    color: COLOR.GREYVIOLET,
    marginBottom: 2,
  },
  detailValue: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_11,
    color: COLOR.DARK,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 6,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  declineBtn: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#FF4444',
  },
  declineBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_11,
    color: '#FF4444',
  },
  offerBtn: {
    backgroundColor: COLOR.BLUE,
  },
  acceptBtn: {
    backgroundColor: COLOR.GREEN,
  },
  actionBtnText: {
    fontFamily: FAMILY.BOLD,
    fontSize: SIZE.SIZE_11,
    color: COLOR.LIGHT,
  },
};
